# fly.toml app configuration file generated for dae01-won on 2025-07-03T15:42:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dae01-won'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
